### ISSUE TITLE
Question about ViT-based on distillation methods like PODNet

### ISSUE THREAD

**Issue by dy1998** [JiahuaDong/HFC#2]
Hello, thanks for your wonderful work. May I ask if PODNet distillates features of all MSA blocks in your ViT-based re-implemented version?

Waiting for your kind reply.

**Comment by JiahuaDong** [comment]
Yes.  of course

**Comment by dy1998** [comment]
> Yes. of course

I also try to get the features of all MSA blocks via timm vit like below:
`model=timm.create_model('vit_base_patch16_224', features_only=True,pretrained=True)`

However, it raised "RuntimeError: features_only not implemented for Vision Transformer models. " I wonder know how to obtain intermediate features of ViT. How did you implement it?

**Comment by dy1998** [comment]
> Yes. of course

Thanks for your answer!
